#The pod won't be accessible to anything outside the cluster unless we write a service file

apiVersion: v1
kind: Service
metadata:
  name: gpu-inference-service
spec:
  type: NodePort
  selector:
    app: gpu-inference # Matches the Pods with same label (from deployment)
  ports:
    - protocol: TCP
      port: 8000          #The port the service exposes inside the cluster
      targetPort: 8000    #The port inside the container my app listens on
      nodePort: 30080     #The port exposed on the host